apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "basicMigrate.fullname" . }}-migrate
  labels:
    {{- include "basicMigrate.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    labels:
      {{- include "basicMigrate.labels" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "basicMigrate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "app"
            - "migrate"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_USER
              value: "username"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_HOST
              value: "mariadb.default.svc"
            - name: DATABASE_NAME
              value: "application"