apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
# app: hello
images:
  - name: lol
    newName: asia-southeast1-docker.pkg.dev/healthy-rarity-238313/code-assess/lol
    newTag: v102
namespace: code-assess
resources:
  - deployment.yaml
