apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-app-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  game.properties: |
    lol: caca
    miao: zzz
  