apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: default
      containers:
      - image: asia-southeast1-docker.pkg.dev/XXX/demo/sample-google-compute:YYY
        imagePullPolicy: IfNotPresent
        name: googlecompute
        env:
        - name: GCP_PROJECT_ID
          value: XXX
        - name: REGION
          value: asia-southeast1-a
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 500Mi
      restartPolicy: Always
