apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: test
build:
  artifacts:
    - image: gcr.io/XXXXX/basicwithstackdriver
      context: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - deployment-manifests/*.yaml
