version: '3.3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    restart: always
    volumes:
      - type: bind
        source: ./secrets/private
        target: /home/jenkins/.ssh/
        read_only: true
  agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./secrets/public
        target: /home/jenkins/.ssh/
        read_only: true