jenkins:
  systemMessage: Jenkins managed via Configuration as Code
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: password
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            entries:
              - user: "authenticated"
  crumbIssuer: "standard" 
  numExecutors: 0
  nodes:
    - permanent:
        labelString: "linux"
        mode: NORMAL
        name: "zzz"
        numExecutors: 4
        remoteFS: "/home/jenkins"
        launcher:
          ssh:
            host: "agent"
            port: 22
            javaPath: "/opt/java/openjdk/bin/java"
            credentialsId: ultimate_ssh_key
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: SYSTEM
              id: admin
              username: admin
              password: password
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ultimate_ssh_key
              username: jenkins
              description: "SSH private key file. Provided via file"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:${SSH_PRIVATE_FILE_PATH}}" 
jobs:
  - file: /home/jobs/01sample.groovy
  - file: /home/jobs/02sample.groovy
  - file: /home/jobs/03sample.groovy

unclassified:
  # scmGit:
  #   addGitTagAction: false
  #   allowSecondFetch: false
  #   createAccountBasedOnEmail: true
  #   disableGitToolChooser: false
  #   globalConfigEmail: jenkins@domain.local
  #   globalConfigName: jenkins
  #   hideCredentials: true
  #   showEntireCommitSummaryInChanges: true
  #   useExistingAccountWithSameEmail: false
  location:
    url: http://localhost:8090
    adminAddress: admin@jenkins.com