apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: custom-hpa-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-hpa-client
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: testservice_generated_queue_item
        target:
          # type: Value
          # value: 1
          type: AverageValue
          averageValue: 10