apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

images:
- name: custom-hpa-client
  newName: test/custom-hpa-client
  newTag: v3

resources:
- deployment.yaml
- hpa.yaml