# Refer to the following documentation page: 
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
# 
# Comment out resources accordingly to which is to be applied
resources:
- all.yaml
# - alteredclient.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      group: apps
      version: v1
      kind: Deployment