apiVersion: v1
kind: Service
metadata:
  labels:
    run: app-1
  name: app-1
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: app-1
  type: NodePort
