# Comment out resources accordingly to which is to be applied
resources:
- deploy.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: leader-election
  newName: leader-election
  newTag: 0.0.12