kind: Service
apiVersion: v1
metadata:
  name: custom-hpa-server
  labels:
    app: custom-hpa-server
    component: custom-hpa-server
spec:
  selector:
    app: custom-hpa-server
    component: custom-hpa-server
  type: ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort:  8080