-- Separate, identically shaped tables keep the two primary-key indexes easy to
-- compare. UUIDv7 values are generated by the study runner because PostgreSQL
-- 17 does not provide a built-in uuidv7() function.
CREATE TABLE IF NOT EXISTS uuid_study_v4 (
    id uuid PRIMARY KEY,
    payload text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS uuid_study_v7 (
    id uuid PRIMARY KEY,
    payload text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
