loki:
  schema_config:
    configs:
      - from: 2020-09-07
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  storageConfig:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 168h
    filesystem:
      directory: /var/loki/chunks
    aws:
      bucketnames: haha
      endpoint: minio1-hl.default.svc.cluster.local:9000
      access_key_id: minio
      secret_access_key: minio123
      insecure: true
      s3forcepathstyle: true
serviceMonitor:
  enabled: true