name: Build and deploy shopping cart

on:
  push:
    branches:
      - "master"
    paths:
      - "Apps/shopping-list/**"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/hairizuan-personal-github/providers/golang-programming"
        service_account: 'github-actions@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com'

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet   

    - name: Setup labels for docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: "asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/personal/shopping-list"
        tags: |
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./Apps/shopping-list
        file: ./Apps/shopping-list/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        provenance: false

    - name: Deploy and update cloud run
      run: |-
        gcloud run deploy shopping-list \
          --image=${{ steps.meta.outputs.tags }} \
          --region=asia-southeast1 \
          --allow-unauthenticated
          
