name: Build and deploy shopping cart

on:
  push:
    branches:
      - "master"
    paths:
      - "Apps/shopping-list/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


